# Generated by Django 5.1.6 on 2025-07-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="group",
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERUSER", "Superuser"),
                    ("ADMIN_GLOBAL", "Admin Global"),
                    ("ADMIN_TERRITORIAL", "Admin Territorial"),
                    ("CHEF_DEPT_TECH", "Chef Département Technique"),
                    ("RESP_OPERATEUR", "Responsable Opérateur de Saisie"),
                ],
                default="RESP_OPERATEUR",
                max_length=32,
            ),
        ),
    ]
