# Generated by Django 5.1.6 on 2025-06-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0003_remove_insured_college_remove_insured_policy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="status",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="payment_method_type",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="payment_type",
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="payment_number",
            field=models.CharField(max_length=255),
        ),
    ]
