# Generated by Django 5.1.6 on 2025-07-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0004_remove_file_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="policy",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
