# Generated by Django 5.1.6 on 2025-07-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0005_alter_claim_id_alter_policy_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
