# Generated by Django 5.1.6 on 2025-07-07 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0006_file_file_name_alter_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="prime",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="ClientPrimeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prime", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prime_history",
                        to="file_upload.client",
                    ),
                ),
            ],
        ),
    ]
